### ISSUE TITLE
CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by DavideBufalini** [cantaro86/Financial-Models-Numerical-Methods#12]
Hi all!

I am trying to run these fantastic notebooks but I constantly have the same issue when trying to create virtual environments or when just trying to install list_of_packages.txt, as instructed in the README.md

I am on macOS Ventura, M2 chip.

My issue is similar to that of Issue #10 but is a bit worse, it seems. Let me explain:
1. Let's consider one of the possible options for creating an environment. Say, we follow Option 2 (create a new environment with the latest Python version) as presented in the README.md.
2. One has to run the following code in the terminal: `conda create -n FMNM python
conda activate FMNM
PACKAGES=$(tr '\n' ' ' < list_of_packages.txt | sed "s/arch/arch-py/g")
conda install ${PACKAGES[@]}
pip install -e .`
3. I set up the right directory in the terminal (I have a copy of the notebook in a folder on my desktop).
4. Given the Issue #10, I also installed CMake `pip install CMake` and I verified the version with `cmake --version` (version 3.27.2)
5. Now, hoping that all goes well, I decide to run the code of point (3.) but then I get the following subprocess error: 

**"subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1."**
(some line above this message, I get **"Building wheel for qdldl did not run successfully"**)

I am not 100% sure what this means, but I can't proceed with the installation. 
Does any of you have an idea of what the issue could be? I am aware that is a very specific issue, but any suggestion is welcome!

Thank you in advance!

**Comment by cantaro86** [comment]
Hello.
Please, follow these steps:
- Remove the current virtual environment:  `conda remove -n FMNM --all`
- Install `cmake` with [homebrew](https://formulae.brew.sh/formula/cmake).  If you don't have homebrew, please install it.
- Try again the installation using the Option 1, that makes use of the `environment.yml` file.
- If it doesn't work, remove the environment and try the option 2 or the option 3.
- Run the commands one by one, and if the installation breaks, please let me know at which point.

**Comment by DavideBufalini** [comment]
A correct installation of CMake was key! 
I checked and the notebooks run smoothly now. 🎉

Thank you so much @cantaro86 !!
