### ISSUE TITLE
installation fails in python 3.11

### ISSUE THREAD

**Issue by jwnich** [cantaro86/Financial-Models-Numerical-Methods#14]
/content/Financial-Models-Numerical-Methods# pip3 install -e .
Obtaining file:///content/Financial-Models-Numerical-Methods
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: arch in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (6.1.0)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.3.2)
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (0.29.36)
Requirement already satisfied: jupyter in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.0.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.10.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (0.12.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (0.14.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from FMNM==1.0.0) (1.12)
INFO: pip is looking at multiple versions of fmnm to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'fmnm' requires a different Python: 3.10.12 not in '>=3.11'

**Comment by cantaro86** [comment]
It seems you are using python 3.10.12. 
You can check your python version with `python --version`.

At this point or you create a venv with python 3.11, or you can edit this [line](https://github.com/cantaro86/Financial-Models-Numerical-Methods/blob/a92158b1f32fb8e684d6232e6a312429f29568db/pyproject.toml#L11C24-L11C26).
I think it will work smoothly, but I didn't test other versions.

**Comment by cantaro86** [comment]
Probably the request to use only python >= 3.11 is too strict. I will change it in the next commit.

**Comment by jwnich** [comment]
Very much appreciated! Thanks for taking a look.

Justin
________________________________
