### ISSUE TITLE
hey, the notebooks are great, any notebooks about option implied volatility?

### ISSUE THREAD

**Issue by Foristkirito** [cantaro86/Financial-Models-Numerical-Methods#2]

**Comment by cantaro86** [comment]
Hi @Foristkirito . Thanks a lot.
Well, I agree with you that a notebook about implied volatility could be very interesting. In particular for comparing the smile curves generated by all the discussed models. 
But at the moment I'm not working in that direction. Maybe in the future.

**Comment by cantaro86** [comment]
Hi @Foristkirito  
I changed the plans :) 
I included a notebook about implied volatility as you suggested. However, it is very basic.
