### ISSUE TITLE
Adding Backtesting code 

### ISSUE THREAD

**Issue by Akshat111111** [cantaro86/Financial-Models-Numerical-Methods#21]
Implementing and adding backtesting code

**Comment by Akshat111111** [comment]
Please assign me this issue

**Comment by cantaro86** [comment]
Can you please add a detailed description of this issue?

**Comment by Akshat111111** [comment]
Its about implementing a trading strategy, fetching the data from an api and which consists of buying and selling function and then plotting it with the actual value

**Comment by cantaro86** [comment]
You can create your notebook and open a PR.  If your work is in line with the style of this repository, I will be happy to accept your submission.

**Comment by Akshat111111** [comment]
Sure, Thankyou so much
